INSERT INTO ACT_ID_TENANT (ID_, REV_, NAME_)
VALUES ('DE', 1, 'German');

INSERT INTO ACT_ID_TENANT (ID_, REV_, NAME_)
VALUES ('FR', 1, 'French');

INSERT INTO ACT_ID_TENANT (ID_, REV_, NAME_)
VALUES ('EN', 1, 'English');
